# Generated by Django 3.2.16 on 2023-07-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_stock_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='receive_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
