# Generated by Django 3.2.16 on 2023-07-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_stock_receive_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='receive_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
